create extension if not exists pgcrypto;

create table if not exists public.expense_evidence (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_id bigint,
  sync_id uuid not null default gen_random_uuid(),
  version integer not null default 1,
  project_name text not null,
  evidence_date timestamptz not null,
  amount numeric,
  currency text not null default 'CNY',
  category text not null default 'invoice',
  status text not null default 'pending',
  merchant text,
  note text,
  remote_storage_path text,
  file_name text,
  mime_type text,
  uploaded_at timestamptz,
  trip_date timestamptz,
  deleted_at timestamptz,
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_expense_evidence_user_sync_id
  on public.expense_evidence(user_id, sync_id);

create index if not exists idx_expense_evidence_user_updated_at
  on public.expense_evidence(user_id, updated_at);

create index if not exists idx_expense_evidence_user_project
  on public.expense_evidence(user_id, project_name);

create index if not exists idx_expense_evidence_deleted_at
  on public.expense_evidence(deleted_at)
  where deleted_at is not null;

drop trigger if exists trg_expense_evidence_bump_sync_metadata
  on public.expense_evidence;
create trigger trg_expense_evidence_bump_sync_metadata
before insert or update on public.expense_evidence
for each row execute function public.bump_sync_metadata();

alter table public.expense_evidence enable row level security;

drop policy if exists "Users can read own expense evidence"
  on public.expense_evidence;
create policy "Users can read own expense evidence"
  on public.expense_evidence
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own expense evidence"
  on public.expense_evidence;
create policy "Users can insert own expense evidence"
  on public.expense_evidence
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own expense evidence"
  on public.expense_evidence;
create policy "Users can update own expense evidence"
  on public.expense_evidence
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('evidence-files', 'evidence-files', false)
on conflict (id) do nothing;

drop policy if exists "Users can read own evidence files"
  on storage.objects;
create policy "Users can read own evidence files"
  on storage.objects
  for select
  using (
    bucket_id = 'evidence-files'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "Users can upload own evidence files"
  on storage.objects;
create policy "Users can upload own evidence files"
  on storage.objects
  for insert
  with check (
    bucket_id = 'evidence-files'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "Users can update own evidence files"
  on storage.objects;
create policy "Users can update own evidence files"
  on storage.objects
  for update
  using (
    bucket_id = 'evidence-files'
    and auth.uid()::text = (storage.foldername(name))[1]
  )
  with check (
    bucket_id = 'evidence-files'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "Users can delete own evidence files"
  on storage.objects;
create policy "Users can delete own evidence files"
  on storage.objects
  for delete
  using (
    bucket_id = 'evidence-files'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
