create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_id bigint,
  name text not null,
  status text not null default 'active',
  sync_id text,
  version integer not null default 1,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.expense_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_id bigint,
  expense_date timestamptz not null,
  amount numeric not null check (amount >= 0),
  currency text not null default 'CNY',
  category text not null default 'other',
  merchant text,
  note text,
  project_name text,
  sync_id text,
  version integer not null default 1,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.bump_sync_metadata()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = coalesce(new.updated_at, now());
  if tg_op = 'UPDATE' then
    new.version = old.version + 1;
  elsif new.version is null then
    new.version = 1;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_projects_bump_sync_metadata on public.projects;
create trigger trg_projects_bump_sync_metadata
before insert or update on public.projects
for each row execute function public.bump_sync_metadata();

drop trigger if exists trg_expense_records_bump_sync_metadata on public.expense_records;
create trigger trg_expense_records_bump_sync_metadata
before insert or update on public.expense_records
for each row execute function public.bump_sync_metadata();

alter table public.projects enable row level security;
alter table public.expense_records enable row level security;

drop policy if exists "projects_select_own" on public.projects;
create policy "projects_select_own"
on public.projects for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "projects_insert_own" on public.projects;
create policy "projects_insert_own"
on public.projects for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "projects_update_own" on public.projects;
create policy "projects_update_own"
on public.projects for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "expense_records_select_own" on public.expense_records;
create policy "expense_records_select_own"
on public.expense_records for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "expense_records_insert_own" on public.expense_records;
create policy "expense_records_insert_own"
on public.expense_records for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "expense_records_update_own" on public.expense_records;
create policy "expense_records_update_own"
on public.expense_records for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create unique index if not exists projects_user_sync_id_uidx
on public.projects(user_id, sync_id)
where sync_id is not null;

create index if not exists projects_user_updated_idx
on public.projects(user_id, updated_at);

create index if not exists projects_deleted_idx
on public.projects(deleted_at)
where deleted_at is not null;

create unique index if not exists expense_records_user_sync_id_uidx
on public.expense_records(user_id, sync_id)
where sync_id is not null;

create index if not exists expense_records_user_updated_idx
on public.expense_records(user_id, updated_at);

create index if not exists expense_records_project_idx
on public.expense_records(user_id, project_name);

create index if not exists expense_records_deleted_idx
on public.expense_records(deleted_at)
where deleted_at is not null;
