-- Baseline schema for new Supabase projects.
-- Photo module remains local-only; only work logs, subscriptions and evidence sync.

create extension if not exists pgcrypto;

create or replace function public.bump_sync_metadata()
returns trigger as $$
begin
  new.updated_at := now();

  if tg_op = 'UPDATE' then
    new.version := old.version + 1;
  elsif new.version is null then
    new.version := 1;
  end if;

  if new.sync_id is null then
    new.sync_id := gen_random_uuid();
  end if;

  return new;
end;
$$ language plpgsql;

create table if not exists public.work_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_id bigint,
  date timestamptz not null,
  type text not null,
  duration double precision,
  project_name text,
  transport text,
  expenses double precision,
  is_reimbursed boolean not null default false,
  notes text,
  sync_id uuid not null default gen_random_uuid(),
  version integer not null default 1,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_id bigint,
  name text not null,
  price double precision,
  cycle text not null,
  start_date timestamptz not null,
  description text,
  sort_index integer,
  sync_id uuid not null default gen_random_uuid(),
  version integer not null default 1,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_work_logs_user_sync_id
  on public.work_logs(user_id, sync_id);

create unique index if not exists uq_subscriptions_user_sync_id
  on public.subscriptions(user_id, sync_id);

create index if not exists idx_work_logs_user_updated_at
  on public.work_logs(user_id, updated_at);

create index if not exists idx_subscriptions_user_updated_at
  on public.subscriptions(user_id, updated_at);

create index if not exists idx_work_logs_deleted_at
  on public.work_logs(deleted_at)
  where deleted_at is not null;

create index if not exists idx_subscriptions_deleted_at
  on public.subscriptions(deleted_at)
  where deleted_at is not null;

drop trigger if exists trg_work_logs_bump_sync_metadata on public.work_logs;
create trigger trg_work_logs_bump_sync_metadata
before insert or update on public.work_logs
for each row execute function public.bump_sync_metadata();

drop trigger if exists trg_subscriptions_bump_sync_metadata on public.subscriptions;
create trigger trg_subscriptions_bump_sync_metadata
before insert or update on public.subscriptions
for each row execute function public.bump_sync_metadata();

alter table public.work_logs enable row level security;
alter table public.subscriptions enable row level security;

drop policy if exists "Users can read own work logs" on public.work_logs;
create policy "Users can read own work logs"
  on public.work_logs
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own work logs" on public.work_logs;
create policy "Users can insert own work logs"
  on public.work_logs
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own work logs" on public.work_logs;
create policy "Users can update own work logs"
  on public.work_logs
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can read own subscriptions" on public.subscriptions;
create policy "Users can read own subscriptions"
  on public.subscriptions
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own subscriptions" on public.subscriptions;
create policy "Users can insert own subscriptions"
  on public.subscriptions
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own subscriptions" on public.subscriptions;
create policy "Users can update own subscriptions"
  on public.subscriptions
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
