-- Split evidence file sync state into a retryable attachment table.

create extension if not exists pgcrypto;

create table if not exists public.evidence_attachments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_id bigint,
  sync_id uuid not null default gen_random_uuid(),
  evidence_sync_id uuid not null,
  version integer not null default 1,
  remote_storage_path text,
  original_file_name text not null,
  content_hash text,
  size_bytes bigint,
  mime_type text,
  upload_state text not null default 'pending'
    check (upload_state in ('pending', 'uploading', 'uploaded', 'failed', 'deleted')),
  uploaded_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_evidence_attachments_user_sync_id
  on public.evidence_attachments(user_id, sync_id);
create index if not exists idx_evidence_attachments_user_evidence_sync_id
  on public.evidence_attachments(user_id, evidence_sync_id);
create index if not exists idx_evidence_attachments_user_updated_at
  on public.evidence_attachments(user_id, updated_at);
create index if not exists idx_evidence_attachments_deleted_at
  on public.evidence_attachments(deleted_at)
  where deleted_at is not null;

drop trigger if exists trg_evidence_attachments_bump_sync_metadata
  on public.evidence_attachments;
create trigger trg_evidence_attachments_bump_sync_metadata
before insert or update on public.evidence_attachments
for each row execute function public.bump_sync_metadata();

alter table public.evidence_attachments enable row level security;

revoke all on table public.evidence_attachments from anon;
grant select, insert, update, delete on table public.evidence_attachments
  to authenticated;

drop policy if exists "evidence_attachments_select_own"
  on public.evidence_attachments;
create policy "evidence_attachments_select_own"
  on public.evidence_attachments
  for select
  using (auth.uid() = user_id);

drop policy if exists "evidence_attachments_insert_own"
  on public.evidence_attachments;
create policy "evidence_attachments_insert_own"
  on public.evidence_attachments
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "evidence_attachments_update_own"
  on public.evidence_attachments;
create policy "evidence_attachments_update_own"
  on public.evidence_attachments
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "evidence_attachments_delete_own"
  on public.evidence_attachments;
create policy "evidence_attachments_delete_own"
  on public.evidence_attachments
  for delete
  using (auth.uid() = user_id);
